/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/test-route'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as InactiveMembersRouteRouteImport } from './routes/inactive-members.route'
import { Route as DeletedRecordsRouteRouteImport } from './routes/deleted-records.route'
import { Route as LayoutMembersIndexRouteImport } from './routes/_layout/members/index'
import { Route as LayoutCouncilFellowshipIndexRouteImport } from './routes/_layout/council-fellowship/index'
import { Route as LayoutSettingsLayoutRouteImport } from './routes/_layout/settings/_layout'
import { Route as LayoutMembersAddRouteImport } from './routes/_layout/members/add'
import { Route as LayoutMembersIdRouteImport } from './routes/_layout/members/$id'
import { Route as LayoutCouncilFellowshipAddRouteImport } from './routes/_layout/council-fellowship/add'
import { Route as LayoutCouncilFellowshipIdRouteImport } from './routes/_layout/council-fellowship/$id'
import { Route as LayoutSettingsLayoutStaffRouteImport } from './routes/_layout/settings/_layout/staff'
import { Route as LayoutSettingsLayoutRoleRouteImport } from './routes/_layout/settings/_layout/role'
import { Route as LayoutSettingsLayoutProfileRouteImport } from './routes/_layout/settings/_layout/profile'

const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test-route',
  path: '/test-route',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const InactiveMembersRouteRoute = InactiveMembersRouteRouteImport.update({
  id: '/inactive-members',
  path: '/inactive-members',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletedRecordsRouteRoute = DeletedRecordsRouteRouteImport.update({
  id: '/deleted-records',
  path: '/deleted-records',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LayoutMembersIndexRoute = LayoutMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCouncilFellowshipIndexRoute =
  LayoutCouncilFellowshipIndexRouteImport.update({
    id: '/council-fellowship/',
    path: '/council-fellowship/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsLayoutRoute = LayoutSettingsLayoutRouteImport.update({
  id: '/settings/_layout',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersAddRoute = LayoutMembersAddRouteImport.update({
  id: '/members/add',
  path: '/members/add',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersIdRoute = LayoutMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCouncilFellowshipAddRoute =
  LayoutCouncilFellowshipAddRouteImport.update({
    id: '/council-fellowship/add',
    path: '/council-fellowship/add',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCouncilFellowshipIdRoute =
  LayoutCouncilFellowshipIdRouteImport.update({
    id: '/council-fellowship/$id',
    path: '/council-fellowship/$id',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsLayoutStaffRoute =
  LayoutSettingsLayoutStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => LayoutSettingsLayoutRoute,
  } as any)
const LayoutSettingsLayoutRoleRoute =
  LayoutSettingsLayoutRoleRouteImport.update({
    id: '/role',
    path: '/role',
    getParentRoute: () => LayoutSettingsLayoutRoute,
  } as any)
const LayoutSettingsLayoutProfileRoute =
  LayoutSettingsLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutSettingsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/deleted-records': typeof DeletedRecordsRouteRoute
  '/inactive-members': typeof InactiveMembersRouteRoute
  '/dashboard': typeof DashboardRoute
  '/test-route': typeof TestRouteRoute
  '/about': typeof AboutLazyRoute
  '/council-fellowship/$id': typeof LayoutCouncilFellowshipIdRoute
  '/council-fellowship/add': typeof LayoutCouncilFellowshipAddRoute
  '/members/$id': typeof LayoutMembersIdRoute
  '/members/add': typeof LayoutMembersAddRoute
  '/settings': typeof LayoutSettingsLayoutRouteWithChildren
  '/council-fellowship': typeof LayoutCouncilFellowshipIndexRoute
  '/members': typeof LayoutMembersIndexRoute
  '/settings/profile': typeof LayoutSettingsLayoutProfileRoute
  '/settings/role': typeof LayoutSettingsLayoutRoleRoute
  '/settings/staff': typeof LayoutSettingsLayoutStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/deleted-records': typeof DeletedRecordsRouteRoute
  '/inactive-members': typeof InactiveMembersRouteRoute
  '/dashboard': typeof DashboardRoute
  '/test-route': typeof TestRouteRoute
  '/about': typeof AboutLazyRoute
  '/council-fellowship/$id': typeof LayoutCouncilFellowshipIdRoute
  '/council-fellowship/add': typeof LayoutCouncilFellowshipAddRoute
  '/members/$id': typeof LayoutMembersIdRoute
  '/members/add': typeof LayoutMembersAddRoute
  '/settings': typeof LayoutSettingsLayoutRouteWithChildren
  '/council-fellowship': typeof LayoutCouncilFellowshipIndexRoute
  '/members': typeof LayoutMembersIndexRoute
  '/settings/profile': typeof LayoutSettingsLayoutProfileRoute
  '/settings/role': typeof LayoutSettingsLayoutRoleRoute
  '/settings/staff': typeof LayoutSettingsLayoutStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/deleted-records': typeof DeletedRecordsRouteRoute
  '/inactive-members': typeof InactiveMembersRouteRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/test-route': typeof TestRouteRoute
  '/about': typeof AboutLazyRoute
  '/_layout/council-fellowship/$id': typeof LayoutCouncilFellowshipIdRoute
  '/_layout/council-fellowship/add': typeof LayoutCouncilFellowshipAddRoute
  '/_layout/members/$id': typeof LayoutMembersIdRoute
  '/_layout/members/add': typeof LayoutMembersAddRoute
  '/_layout/settings/_layout': typeof LayoutSettingsLayoutRouteWithChildren
  '/_layout/council-fellowship/': typeof LayoutCouncilFellowshipIndexRoute
  '/_layout/members/': typeof LayoutMembersIndexRoute
  '/_layout/settings/_layout/profile': typeof LayoutSettingsLayoutProfileRoute
  '/_layout/settings/_layout/role': typeof LayoutSettingsLayoutRoleRoute
  '/_layout/settings/_layout/staff': typeof LayoutSettingsLayoutStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deleted-records'
    | '/inactive-members'
    | '/dashboard'
    | '/test-route'
    | '/about'
    | '/council-fellowship/$id'
    | '/council-fellowship/add'
    | '/members/$id'
    | '/members/add'
    | '/settings'
    | '/council-fellowship'
    | '/members'
    | '/settings/profile'
    | '/settings/role'
    | '/settings/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deleted-records'
    | '/inactive-members'
    | '/dashboard'
    | '/test-route'
    | '/about'
    | '/council-fellowship/$id'
    | '/council-fellowship/add'
    | '/members/$id'
    | '/members/add'
    | '/settings'
    | '/council-fellowship'
    | '/members'
    | '/settings/profile'
    | '/settings/role'
    | '/settings/staff'
  id:
    | '__root__'
    | '/'
    | '/deleted-records'
    | '/inactive-members'
    | '/_layout'
    | '/dashboard'
    | '/test-route'
    | '/about'
    | '/_layout/council-fellowship/$id'
    | '/_layout/council-fellowship/add'
    | '/_layout/members/$id'
    | '/_layout/members/add'
    | '/_layout/settings/_layout'
    | '/_layout/council-fellowship/'
    | '/_layout/members/'
    | '/_layout/settings/_layout/profile'
    | '/_layout/settings/_layout/role'
    | '/_layout/settings/_layout/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DeletedRecordsRouteRoute: typeof DeletedRecordsRouteRoute
  InactiveMembersRouteRoute: typeof InactiveMembersRouteRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  TestRouteRoute: typeof TestRouteRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-route': {
      id: '/test-route'
      path: '/test-route'
      fullPath: '/test-route'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inactive-members': {
      id: '/inactive-members'
      path: '/inactive-members'
      fullPath: '/inactive-members'
      preLoaderRoute: typeof InactiveMembersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deleted-records': {
      id: '/deleted-records'
      path: '/deleted-records'
      fullPath: '/deleted-records'
      preLoaderRoute: typeof DeletedRecordsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/members/': {
      id: '/_layout/members/'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof LayoutMembersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/council-fellowship/': {
      id: '/_layout/council-fellowship/'
      path: '/council-fellowship'
      fullPath: '/council-fellowship'
      preLoaderRoute: typeof LayoutCouncilFellowshipIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/_layout': {
      id: '/_layout/settings/_layout'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members/add': {
      id: '/_layout/members/add'
      path: '/members/add'
      fullPath: '/members/add'
      preLoaderRoute: typeof LayoutMembersAddRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members/$id': {
      id: '/_layout/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof LayoutMembersIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/council-fellowship/add': {
      id: '/_layout/council-fellowship/add'
      path: '/council-fellowship/add'
      fullPath: '/council-fellowship/add'
      preLoaderRoute: typeof LayoutCouncilFellowshipAddRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/council-fellowship/$id': {
      id: '/_layout/council-fellowship/$id'
      path: '/council-fellowship/$id'
      fullPath: '/council-fellowship/$id'
      preLoaderRoute: typeof LayoutCouncilFellowshipIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/_layout/staff': {
      id: '/_layout/settings/_layout/staff'
      path: '/staff'
      fullPath: '/settings/staff'
      preLoaderRoute: typeof LayoutSettingsLayoutStaffRouteImport
      parentRoute: typeof LayoutSettingsLayoutRoute
    }
    '/_layout/settings/_layout/role': {
      id: '/_layout/settings/_layout/role'
      path: '/role'
      fullPath: '/settings/role'
      preLoaderRoute: typeof LayoutSettingsLayoutRoleRouteImport
      parentRoute: typeof LayoutSettingsLayoutRoute
    }
    '/_layout/settings/_layout/profile': {
      id: '/_layout/settings/_layout/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutSettingsLayoutProfileRouteImport
      parentRoute: typeof LayoutSettingsLayoutRoute
    }
  }
}

interface LayoutSettingsLayoutRouteChildren {
  LayoutSettingsLayoutProfileRoute: typeof LayoutSettingsLayoutProfileRoute
  LayoutSettingsLayoutRoleRoute: typeof LayoutSettingsLayoutRoleRoute
  LayoutSettingsLayoutStaffRoute: typeof LayoutSettingsLayoutStaffRoute
}

const LayoutSettingsLayoutRouteChildren: LayoutSettingsLayoutRouteChildren = {
  LayoutSettingsLayoutProfileRoute: LayoutSettingsLayoutProfileRoute,
  LayoutSettingsLayoutRoleRoute: LayoutSettingsLayoutRoleRoute,
  LayoutSettingsLayoutStaffRoute: LayoutSettingsLayoutStaffRoute,
}

const LayoutSettingsLayoutRouteWithChildren =
  LayoutSettingsLayoutRoute._addFileChildren(LayoutSettingsLayoutRouteChildren)

interface LayoutRouteChildren {
  LayoutCouncilFellowshipIdRoute: typeof LayoutCouncilFellowshipIdRoute
  LayoutCouncilFellowshipAddRoute: typeof LayoutCouncilFellowshipAddRoute
  LayoutMembersIdRoute: typeof LayoutMembersIdRoute
  LayoutMembersAddRoute: typeof LayoutMembersAddRoute
  LayoutSettingsLayoutRoute: typeof LayoutSettingsLayoutRouteWithChildren
  LayoutCouncilFellowshipIndexRoute: typeof LayoutCouncilFellowshipIndexRoute
  LayoutMembersIndexRoute: typeof LayoutMembersIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCouncilFellowshipIdRoute: LayoutCouncilFellowshipIdRoute,
  LayoutCouncilFellowshipAddRoute: LayoutCouncilFellowshipAddRoute,
  LayoutMembersIdRoute: LayoutMembersIdRoute,
  LayoutMembersAddRoute: LayoutMembersAddRoute,
  LayoutSettingsLayoutRoute: LayoutSettingsLayoutRouteWithChildren,
  LayoutCouncilFellowshipIndexRoute: LayoutCouncilFellowshipIndexRoute,
  LayoutMembersIndexRoute: LayoutMembersIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DeletedRecordsRouteRoute: DeletedRecordsRouteRoute,
  InactiveMembersRouteRoute: InactiveMembersRouteRoute,
  LayoutRoute: LayoutRouteWithChildren,
  DashboardRoute: DashboardRoute,
  TestRouteRoute: TestRouteRoute,
  AboutLazyRoute: AboutLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
